### PR TITLE
Added code for using value of "retry-after" header as waiting time if status_code = 429

### PR DESCRIPTION
**Pull request by nielsoledam**
Just a suggestion of a small code change in order to make the call use the waiting time suggested by the remote server if status_code 429 is experienced and the "retry_after" header has been supplied.

### CODE REVIEW

**Comment by hadley** [comment]
The code inside `backoff_full_jitter()` has changed quite a bit, and it feels more natural to implement there now. I'd be happy to review a new PR.

**Comment by nielsoledam** [comment]
Cool – I'll update my code sometime next week and send new pull request.

**Comment by hadley** [comment]
Is there any chance you can make it sooner? (i.e. by Monday). Otherwise it'll need to wait until the next release

**Comment by nielsoledam** [comment]
Thanks for the info – I'll try to squeese it in during the weekend if possible.

**Pull request closed without merging**
