### PR TITLE
Auto-close browser page after successful OAuth

### PR DESCRIPTION
**Pull request by krlmlr**
Only if JavaScript is enabled.

http://stackoverflow.com/a/12791753/946850

### CODE REVIEW

**Comment by saurfang** [comment]
Yes please. One less friction. Any concerns?

**Comment by krlmlr** [comment]
Works well for me in Chromium on Ubuntu. Don't know about other browsers/OSs.

**Comment by jennybc** [comment]
It doesn't seem to be working for me (Mac OS / Safari 10.1) 😞. This *would* be really nice.

**Comment by hadley** [comment]
Won't this just close the tab, leaving the user in the browser with no idea what to do next?

**Comment by krlmlr** [comment]
That's true. I guess we could add a close button and an "auto-close all future such windows" checkbox.

@jennybc: All this PR does is showing an HTML file with a tiny bit of JavaScript. Can you post/show a self-closing HTML document that works on your system?

**Comment by jennybc** [comment]
@krlmlr If I visit an html file with this snippet, it does indeed lead to the associate Safari tab being closed after a short delay.

```
<script type="text/javascript">setTimeout("window.close();", 3000);</script>
```

so I am not sure why my trial of this PR does not lead to autoclose of the tab where I completed OAuth. I just checked one more time, though, and it still doesn't close the tab.

**Comment by krlmlr** [comment]
Strange. When testing this PR, did you notice an alert by Safari that JavaScript is blocked? What happens if you start Safari from the command line and pass it the HTML file from this PR?

**Comment by yutannihilation** [comment]
This doesn't work for my Firefox. While it seems possible to close windows in Chrome, Firefox is still too secure to close window by script:
https://stackoverflow.com/a/19768082/5397672

**Comment by hadley** [comment]
This seems too fragile for minimal gain. I think the current behaviour needs to stay.

**Pull request closed without merging**
